library(shiny)
library(dplyr)
library(fastDummies)
library(kableExtra)
library(ggplot2)
library(gridExtra)
library(grid)
source('R/graphing.R', local = TRUE)
source('R/conditional_table.R', local = TRUE)
load("shiny_data/all_votes.rda")
load("shiny_data/num_selected.rda")
load("shiny_data/cond_tables.rda")
