library(shiny)
library(dplyr)
library(fastDummies)
library(kableExtra)
library(ggplot2)
library(gridExtra)
library(leaflet)
library(rgdal)
library(grid)
library(scales)
source('R/graphing.R', local = TRUE)
source('R/map.R', local = TRUE)
source('R/conditional_table.R', local = TRUE)
load("shiny_data/all_votes.rda")
load("shiny_data/num_selected.rda")
load("shiny_data/cond_tables.rda")
load("shiny_data/results_prep.rda")
load("shiny_data/max_choices.rda")


